plugins {
    id 'com.android.application'
}

android {
    namespace 'com.biruk.androidbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.biruk.androidbridge'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

android {
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
